### ISSUE TITLE
[topic] Using web components - styling

### ISSUE THREAD

**Issue by alangdm** [webcomponents-cg/docs-and-guides#19]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of request

I want to try writing the styling subsection for the "using web components" section of the outline.

I'm thinking of doing an example heavy piece (somewhat similar to [this article I previously wrote](https://dev.to/alangdm/the-quirks-of-shadow-dom-and-how-to-take-advantage-of-them-4cd1) but with a different format.)

Note: I was thinking of writing the Shadow DOM side, but having one for styling non-shadow DOM custom elements would be good too

### Are you interested in authoring this content?

- [X] Yes

**Comment by Westbrook** [comment]
I know @castastrophe loves styling web components, maybe she has some thoughts here or for the PR?
